Repository antrc2/SuperBee_DATN, pull requests merged in 2025-06, with the labels that each got.

#98 Fix/database lan2
  Frontend/src/components/Client/layout/Header.jsx
  backend/database/migrations/2025_05_14_044939_create_superbee_table.php
  backend/database/migrations/2025_05_14_064043_add_foreign_keys_to_superbee_tables.php
Labels: bug, fix

#99 Fix/databaseeee
  backend/database/migrations/2025_05_14_044939_create_superbee_table.php
  backend/database/migrations/2025_05_14_064043_add_foreign_keys_to_superbee_tables.php
Labels: bug

#101 add AffiliateHistory and User Model
  .gitignore
  .vscode/PythonImportHelper-v2-Completion.json
  backend/app/Models/AffiliateHistory.php
  backend/app/Models/RechargeCard.php
  backend/app/Models/User.php
  backend/database/migrations/2025_05_14_044939_create_superbee_table.php
  backend/database/migrations/2025_05_14_064043_add_foreign_keys_to_superbee_tables.php
  backend/database/seeders/DataSeed.php
Labels: bug, fix

#105 Fix/register sus
  Frontend/src/contexts/AuthContext.jsx
  Frontend/src/pages/Auth/Register.jsx
  backend/app/Http/Controllers/Auth/AuthController.php
  backend/app/Http/Middleware/JWTMiddleware.php
  backend/routes/api.php
Labels: feature

#113 upload_admin_users
  Frontend/public/data.json
  Frontend/src/layouts/Admin/AppSidebar.jsx
  Frontend/src/pages/Admin/Account/AccountPage.jsx
  Frontend/src/pages/Admin/Account/ShowAccountPage.jsx
  Frontend/src/pages/Auth/Register.jsx
  Frontend/src/pages/index.jsx
  Frontend/src/routers/Admin.jsx
  Frontend/src/routers/AdminModules.js
  Frontend/src/utils/hook.js
  backend/app/Http/Controllers/UserController.php
  backend/routes/api.php
Labels: feature

#112 Fix/info user
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/contexts/AuthContext.jsx
  Frontend/src/pages/Clients/Profile/ChangePassword.jsx
  Frontend/src/pages/Clients/Profile/Profile.jsx
  Frontend/src/utils/tokenUtils.js
  backend/app/Http/Controllers/User/UserProfileController.php
  backend/app/Http/Middleware/JWTMiddleware.php
  backend/routes/api.php
Labels: fix

#116 add CRU products
  backend/app/Http/Controllers/Admin/AdminProductController.php
  backend/app/Http/Controllers/Callback/BankController.php
  backend/app/Http/Controllers/Callback/CardController.php
  backend/app/Http/Controllers/User/UserProductController.php
  backend/routes/api.php
Labels: bug, feature, fix

#119 Fix database, remove somethings
  Python/Transactions/app.py
  backend/.env.example
  backend/app/Http/Controllers/Admin/AdminDonatePromotionController.php
  backend/app/Http/Controllers/Callback/CardController.php
  backend/app/Models/DonatePromotion.php
  backend/app/Models/ProductCredential.php
  backend/app/Models/ProductGameAttribute.php
  backend/app/Models/ProductImage.php
  backend/database/migrations/2025_05_14_044939_create_superbee_table.php
  backend/database/seeders/DataSeed.php
  backend/routes/api.php
Labels: fix

#120 Fix/database final
  backend/app/Http/Controllers/Admin/AdminDonatePromotionController.php
  backend/app/Models/DonatePromotion.php
  backend/app/Models/Withdraw.php
  backend/database/migrations/2025_05_14_044939_create_superbee_table.php
  backend/database/migrations/2025_05_14_064043_add_foreign_keys_to_superbee_tables.php
  backend/database/seeders/DataSeed.php
  backend/routes/api.php
Labels: fix

#122 add donate card
  backend/app/Http/Controllers/Admin/AdminDonatePromotionController.php
  backend/app/Http/Controllers/Callback/CardController.php
  backend/app/Models/User.php
  backend/app/Models/WalletTransaction.php
  backend/routes/api.php
Labels: feature

#123 add card callback and process donate promotion if exists
  backend/app/Http/Controllers/Callback/BankController.php
  backend/app/Http/Controllers/Callback/CardController.php
  backend/database/migrations/2025_05_14_044939_create_superbee_table.php
  backend/routes/api.php
Labels: feature

#129 change to SePay
  backend/.env.example
  backend/app/Http/Controllers/Callback/BankController.php
  backend/routes/api.php
Labels: feature

#130 fix router and fix transaction date
  backend/app/Http/Controllers/Callback/BankController.php
  backend/routes/api.php
Labels: feature, fix

#136 add accept, deny, cancel product adn fix somethings
  Frontend/public/data.json
  backend/app/Http/Controllers/Admin/AdminProductController.php
  backend/app/Http/Controllers/Callback/BankController.php
  backend/routes/api.php
Labels: feature, fix

#141 Fix/hehe
  backend/routes/api.php
Labels: feature

#157 fix check product_id in cart
  backend/app/Http/Controllers/User/UserOrderController.php
  backend/routes/api.php
Labels: fix

#175 fix/orders_purchase
  backend/app/Http/Controllers/User/UserOrderController.php
Labels: feature, fix
